export const FETCH_INIT_BOOK = "FETCH_INIT_BOOK";
export const FETCH_SUCCESS_BOOK = "FETCH_SUCCESS_BOOK";
export const FETCH_FAILURE_BOOK = "FETCH_FAILURE_BOOK";
export const DELETE_BOOK = "DELETE_BOOK";
export const SELECTED_BOOK = "SELECTED_BOOK";
export const UNSELECTED_BOOK = "UNSELECTED_BOOK";

export const FETCH_INIT_CATEGORY = "FETCH_INIT_CATEGORY";
export const FETCH_SUCCESS_CATEGORY = "FETCH_SUCCESS_CATEGORY";
export const FETCH_FAILURE_CATEGORY = "FETCH_FAILURE_CATEGORY";
export const SELECTED_CATEGORY = "SELECTED_CATEGORY";
